### PR TITLE
Clear errors when new file is uploaded

### LINKED ISSUE #1686: User avatar: error message(s) not cleared
### Steps to reproduce the error

Upload a file type not allowed. Relevant error message is displayed. Upload an allowed file type.

### Actual behavior

Error message is not cleared from first failed attempt.

screen shot 2017-08-01 at 2 27 21 pm

### Expected behavior

Error message should be cleared when new file upload is attempted.

### PR DESCRIPTION
**Pull request by oliverroick**
Changed the JS so that errors are cleared everytime a new file is selected. This should fix [Cadasta:#1686](https://github.com/Cadasta/cadasta-platform/issues/1686).

### CODE REVIEW

**Review by seav — CHANGES_REQUESTED** [review]
Since you are clearing errors whenever the user selects a file, it seems you don't actually need to clear it again when the user encounters an error [here](https://github.com/Cadasta/django-buckets/pull/34/files#diff-1432dc8aeb4711d6d57a77649769e217R50) and when the user does not encounter an error [here](https://github.com/Cadasta/django-buckets/pull/34/files#diff-1432dc8aeb4711d6d57a77649769e217R65), right?

**Comment by oliverroick** [comment]
`error(el, msg)` could be called from anywhere, not just as a result of a new upload. The current work flow doesn't require clearing errors when a new error occurs you're right on that. But I would leave as it is, if only for clarity: When a new file is uploaded, errors are cleared and when a new error occurs. That way we're on the safe side if we ever change the workflow in the future.

**Comment by seav** [comment]
Understood. In that case, maybe you can replace [this line](https://github.com/Cadasta/django-buckets/pull/34/files#diff-1432dc8aeb4711d6d57a77649769e217R65) with a call to `clearErrors()` since it does the exact same thing?

**Comment by oliverroick** [comment]
Yes, that makes sense. It's changed now

**Review by seav — APPROVED** [review]

**Pull request merged**
